This is makeindex, version 2.15 [TeX Live 2015] (kpathsea + Thai support).
Scanning style file ./theisis_master.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file theisis_master.acn....done (78 entries accepted, 0 rejected).
Sorting entries....done (507 comparisons).
Generating output file theisis_master.acr....done (144 lines written, 0 warnings).
Output written in theisis_master.acr.
Transcript written in theisis_master.alg.
